-- =============================================================================
-- V1 - Schema inicial da locadora "Godzilla Local Filmes"
-- =============================================================================
-- Migracoes Flyway sao IMUTAVEIS: uma vez aplicada, esta versao nunca e editada.
-- Qualquer mudanca de schema entra como um novo arquivo V2, V3... Isso garante
-- que qualquer ambiente chegue ao mesmo estado seguindo a mesma sequencia.


-- -----------------------------------------------------------------------------
-- filme
-- -----------------------------------------------------------------------------
CREATE TABLE filme (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo  VARCHAR(200) NOT NULL,
    diretor VARCHAR(150),

    -- O desafio pede busca "por titulo ou ano", embora o JSON de exemplo do
    -- enunciado nao traga esse campo. Prevalece o texto do requisito.
    ano     SMALLINT,

    estoque INTEGER      NOT NULL DEFAULT 0,

    -- Ultima linha de defesa do estoque: mesmo que um bug na aplicacao tente
    -- decrementar alem do disponivel, o banco recusa.
    CONSTRAINT ck_filme_estoque_nao_negativo CHECK (estoque >= 0)
);


-- -----------------------------------------------------------------------------
-- usuario
-- -----------------------------------------------------------------------------
CREATE TABLE usuario (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(150) NOT NULL,
    email      VARCHAR(180) NOT NULL,

    -- Guarda o HASH BCrypt, nunca a senha em texto puro. O nome da coluna e
    -- proposital: deixa obvio, para quem le o schema, que nao ha senha
    -- recuperavel aqui.
    senha_hash VARCHAR(100) NOT NULL,

    criado_em  TIMESTAMPTZ  NOT NULL,

    -- O e-mail e normalizado para minusculas na camada de servico antes de
    -- chegar aqui, entao esta unicidade simples ja e case-insensitive na
    -- pratica, e o mesmo indice atende as consultas de login.
    CONSTRAINT uk_usuario_email UNIQUE (email)
);


-- -----------------------------------------------------------------------------
-- aluguel
-- -----------------------------------------------------------------------------
CREATE TABLE aluguel (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filme_id     BIGINT      NOT NULL,
    usuario_id   BIGINT      NOT NULL,
    alugado_em   TIMESTAMPTZ NOT NULL,

    -- NULL significa "aluguel em aberto". Modelar assim, em vez de um booleano
    -- "ativo", preserva o historico completo de alugueis do cliente e habilita
    -- o indice unico parcial logo abaixo.
    devolvido_em TIMESTAMPTZ,

    CONSTRAINT fk_aluguel_filme   FOREIGN KEY (filme_id)   REFERENCES filme (id),
    CONSTRAINT fk_aluguel_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

-- =============================================================================
-- REGRA CENTRAL DO DESAFIO
-- =============================================================================
-- O enunciado exige que "so e permitido que um cliente alugue um filme de cada
-- vez" e que o banco "garanta a unicidade, apenas 1 registro por aluguel".
--
-- Este e um indice unico PARCIAL: a restricao vale somente para as linhas em que
-- devolvido_em IS NULL, ou seja, os alugueis EM ABERTO. Consequencias:
--
--   - o mesmo usuario pode ter varios alugueis ja devolvidos no historico;
--   - mas nunca dois em aberto ao mesmo tempo.
--
-- A garantia e do BANCO, nao de um "if" na aplicacao. Um "SELECT ... IF ...
-- INSERT" falha sob concorrencia: duas requisicoes simultaneas passam pelo IF
-- juntas, antes de qualquer uma inserir. Aqui, o segundo INSERT e rejeitado pelo
-- proprio PostgreSQL, sem excecao possivel.
CREATE UNIQUE INDEX uk_aluguel_ativo_por_usuario
    ON aluguel (usuario_id)
    WHERE devolvido_em IS NULL;
