CREATE TABLE filme (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo  VARCHAR(200) NOT NULL,
    diretor VARCHAR(150),
    ano     SMALLINT,
    estoque INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT ck_filme_estoque_nao_negativo CHECK (estoque >= 0)
);

CREATE TABLE usuario (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(150) NOT NULL,
    email      VARCHAR(180) NOT NULL,
    -- Guarda o hash BCrypt, nunca a senha.
    senha_hash VARCHAR(100) NOT NULL,
    criado_em  TIMESTAMPTZ  NOT NULL,

    CONSTRAINT uk_usuario_email UNIQUE (email)
);

CREATE TABLE aluguel (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filme_id     BIGINT      NOT NULL,
    usuario_id   BIGINT      NOT NULL,
    alugado_em   TIMESTAMPTZ NOT NULL,
    -- NULL significa aluguel em aberto.
    devolvido_em TIMESTAMPTZ,

    CONSTRAINT fk_aluguel_filme   FOREIGN KEY (filme_id)   REFERENCES filme (id),
    CONSTRAINT fk_aluguel_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

-- Regra central do desafio: "um filme de cada vez" e "apenas 1 registro por
-- aluguel". Indice unico PARCIAL, valido so para alugueis em aberto: o cliente
-- pode ter historico, mas nunca dois ativos. A garantia e do banco, e nao de um
-- IF na aplicacao, que nao resiste a requisicoes simultaneas.
CREATE UNIQUE INDEX uk_aluguel_ativo_por_usuario
    ON aluguel (usuario_id)
    WHERE devolvido_em IS NULL;
